title: Read ME
description: How to use GitHub collaborate on documents
template:
  repo: read-me-template
  name: read-me
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
